name: data
on:
  schedule:
    - cron:  '0 * * * *'
    - cron:  '5 * * * *'
    - cron:  '10 * * * *'
    - cron:  '15 * * * *'    
    - cron:  '20 * * * *'
    - cron:  '25 * * * *'    
    - cron:  '30 * * * *'
    - cron:  '35 * * * *'
    - cron:  '40 * * * *'
    - cron:  '45 * * * *'
    - cron:  '50 * * * *'
    - cron:  '55 * * * *'

jobs:
  generate:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run update-arena

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./data
          destination_dir: data
          keep_files: true
